id: IEA7345AE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:32:54+00:00'
last_modified: '2022-06-08T13:35:56.841964+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20065
  title: གཞན་ཕན་ཟླ་ཤེལ་ནོར་བུའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    C501:
      image_group_id: I1KG21872
      title: ''
      total_pages: 330
      order: 1
      base_file: C501.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
