id: P010437
initial_creation_type: ocr
source_metadata:
  id: bdr:W20065
  title: གཞན་ཕན་ཟླ་ཤེལ་ནོར་བུའི་སྒྲོན་མེ།
  author: ''
  volumes:
    700465900f6b4f2abe38676cee40e97b:
      image_group_id: I1KG21872
      title: ''
      volume_number: 1
      total_pages: 330
      base_file: v001.txt
